- .editorconfig
- .jshintrc
- .npmignore
- CHANGELOG.md
- README.md
- bower.json
- example/index.html
- package.json
- react-tagsinput.css
- react-tagsinput.js
* Add [UMD](https://github.com/umdjs/umd) support
* Get rid of warnings `"Something is calling a React component directly. Use a factory or JSX instead"`
* Get rid of deprecated `transferPropsTo`
* Update CSS styles
* Add usage example
> Update to avoid deprecations of React 0.12.0, add examples, update docs and related

- bower.json
- package.json
Please merge this and republish plugin to NPM (`npm publish .`) and Bower (`git tag 0.2.2` and then `git push --tags`).
See - http://react-components.com/
> add tag to be present in http://react-components.com/

- react-tagsinput.css
I was initially deterred by some of the dimensions in your demo, especially the expanding container after adding a tag. While it's clear that anyone can easily change the styles, the small changes in this commit might yield a more compelling demo.
> nicer style dimensions

- react-tagsinput.js
This change allows users of the `react-tagsinput` component to set the
CSS classes of the sub-elements of the component themselves.
It's very useful when you already have a stylesheet in place or if you
need to adhere to a naming scheme for your classes (like SuitCSS).
> Allow users to set their own classes for elements

- react-tagsinput.js
- test/index.js
I have a hybrid React app which uses react-tagsinput. In some cases I wanted to be able to prevent form submission unless at least one tag is entered.
> Allow preventing form submission

- README.md
- react-tagsinput.js
- test/index.js
Hey, I'm using your neat component in a project and I stumbled upon this while trying to limit the size of a tag before sending it to API.
It's a very small change, but I've wrote a test for it and updated the docs anyway.
> Add new property `maxTagLength` to limit the max length of the input

- react-tagsinput.js
hey @olahol 
Added a name property to the Input component, so that it can be added like so, <TagsInput ref='tags' name="tags" onTagAdd={this._addTag} />. Important for form submissions on server side. 
Please review and merge.
Thank you, 
Gaurav
> Add name property/Prop to input

- src/index.js
- test/index.js
This PR adds the ability to create a new tag with the eventual content that is inside the input field when the input itself loses focus (blur).
Use case:
* user is tabbing through the fields of a form
* one of them is `react-tagsinput`
* user only puts one tag and tabs away
* user submits the form, and no tags has been saved 
Now, as soon as he "blurs" the input, a new tag will be added.
<hr /> 
On an unrelated note, these tests have no `assert`: https://github.com/olahol/react-tagsinput/blob/master/test/index.js#L206-L225, so their basically testing nothing except that no exception is thrown.  
Is that on purpose?
> addOnBlur: add prop to add the content of input as tag when it loses focus

- react-tagsinput.css
Use bootstrap's `×` character for the cross in each tag, which IMO is nicer than an `x`. Will look like this:
> Use nicer × character for cross

- src/index.js
- test/index.js
Added a prop called `validationRegex` that enforces matching for tags. Useful for formatted input, i.e. email addresses.
> Validation regex

- src/index.js
`handleOnBlur` method was missing regex validation so i have added it. I think it makes sense to have regex validation in this method as well since it add the tag.
> Added regex validation in blur method

- README.md
- react-tagsinput.css
- react-tagsinput.js
- src/index.js
- test/index.js
Hey there!
This PR introduce an option to add a class when the input is focused. Here are the detailed changes:
* The wrapper now tracks the focused state through `state.isFocused`
* The `blur` and `focus` methods now properly triggers the onFocus and onBlur behaviors
* Until now, programatically bluring the input wasn't triggering handleOnBlur which contains the logic for such event. It's still not fully fixed though as it's expecting a DOM event and won't add a tag if called by `.blur()`.
* There's now a `focusedClassName` option with a default value of `react-tagsinput--focused`. The demo has been updated so you can have a quick look at the benefits of this feature.
* I've added the relevant tests, along with some more regarding the wrapper's className.
> add option to add a class on focus

- react-tagsinput.js
- src/index.js
Preventing the tab's behavior makes sense if it's actually triggering something else but shouldn't break keyboard navigation otherwise.
Note: given the current implementation of `addTags`, it can hardly return whether or not it actually added a tag. So there are still some cases where the tab key could be prevented erroneously. It'd be better to rely on `addTags`' return value to preventDefault.
> do not prevent tab behavior when not adding a tag

- README.md
- react-tagsinput.js
- src/index.js
For an autocomplete to work with react-tagsinput, it has to have a way to add a tag when selecting a suggestion (via pressing the enter key or clicking on an entry).
> pass addTag to renderInput

- README.md
- react-tagsinput.js
- src/index.js
- test/index.js
This PR adds a way to have tags not being just a string but an object. Once again, it's especially useful when you have an autocomplete that suggests tags with an id and other properties.
> add tagDisplayProp option

- README.md
- src/index.js
- test/index.js
Hi @olahol,
In #94 I added a new property `currentValue` but apparently I also introduced a small bug with this.
When `componentWillReceiveProps` was called but the `currentValue` wasn't set it will set the internal state of `tag` to undefined, which shouldn't be the expected behavior.
I added a condition in `componentWillReceiveProps` to prevent this from happening by making an early return. I also added tests to make sure this behavior is covered.
Thanks again for react-tagsinput!
> Fix current value prop

- react-tagsinput.js
- src/index.js
as pointed out in https://github.com/olahol/react-tagsinput/issues/100
> Using the autocomplete example on example/index.html, if you type the first few letters of a state and then use the down arrow key to choose the state and press Enter to select it, the actual tag created is not the suggestion, but the letters typed so far. Selecting the state suggestion with the mouse works as expected.
Using this code in addition to this pull request solve the problem.
```
let handleOnChange = (event, {newValue, method}) => {
if(method === 'enter') {
event.preventDefault()
} else {
props.onChange(event)
}
}
return (
<Autosuggest
inputProps={{...other, onChange: handleOnChange}}
otherFields...
/>
)
```
> avoid add tag when event is prevented (Compatibility with react-autosuggest)

- react-tagsinput.js
- src/index.js
Hi, in my setup I am passing objects as tags, and using their properties in renderTag function, and was disappointed that in newer version passing objects wasn't working anymore. Have made a fix for that!
Thank you, Alex
> Returned back ability to add non-string entities as tags

- README.md
- src/index.js
- test/index.js
I want to provide some feedback to user when his tags are rejected, it's pretty confusing when tags are just disappearing.
Added a callback `onValidationReject` when tags are rejected through `validationRegex`
> Add onValidationReject callback

- README.md
- package.json
- react-tagsinput.js
- src/index.js
- test/index.js
This is what I was thinking regarding #134
Essentially allows for following behaviour:
- Type tag
- Press return
- Tag added
- Press return again
- Form submits
Open to comments on the implementation however as went back and forth on it a bit and needed this for a bit of a deadline.
I've added sinon to spy on events in the test suite also, wasn't sure what the reaction would be to this so thats up for grabs also...
> Added preventSubmit prop to allow for submiting a form 

- README.md
It's a bit confusing that this function isn't called if you don't set inputValue, it's probably good to be explicit about that in the readme. We found out the solution by looking at this issue https://github.com/olahol/react-tagsinput/issues/123
> Document that onChangeInput is only called when inputValue is set

- react-tagsinput.js
- src/index.js
- test/index.js
Per #155 this PR allows the component to listen for keyboard events via their `key` names as well as the deprecated `keyCode`. `indexOf` is type sensitive so this should not be a breaking change, as `keyCode`s are numbers and `key` names are strings.
> Match on key as well as keyCode

- react-tagsinput.js
- src/index.js
Hello,
Thanks for the library!
Fixed [#213](https://github.com/olahol/react-tagsinput/issues/213). I was able to reproduce this issue when the field is focused and clicked outside the input. Please review this PR and let me know your comments.
> #213: Fixed empty tag added on blur
